### ISSUE TITLE
Problem with store change (back button)

### ISSUE THREAD

**Issue by raymondidema** [reloadseo/magento-plugin#2]
Problem with changing store and opening product. If you click on the back button you will get an error, about $this->getCollection() doesn't exists.

**Comment by jeljer-te-wies** [comment]
Hi Raymond, 

Thanxs for opening an issue! 
We will have a fix tomorrow and let you know as soon as it is on Github.
If you have any problem, don't hesitate to contact us!

Kind regard,
Jeljer te Wies
Reload SEO
