### ISSUE TITLE
Mage registry key "seo_score" already exists

### ISSUE THREAD

**Issue by barryvdh** [reloadseo/magento-plugin#5]
I tried your ReloadSEO plugin with Magento 1.8.1 and it crashed the front-end with the error  'Mage registry key "seo_score" already exists'. I'm using version 1.2.1 from the website (Reload_Seo-1.0.0.zip).

The backed does work correctly. Any ideas?

```
a:5:{i:0;s:44:"Mage registry key "seo_score" already exists";i:1;s:6325:"#0 /home/user/domains/domain.com/public_html/app/Mage.php(223): Mage::throwException('Mage registry k...')
#1 /home/user/domains/domain.com/public_html/app/code/community/Reload/Seo/Model/Observer.php(66): Mage::register('seo_score', Object(Reload_Seo_Model_Score))
#2 /home/user/domains/domain.com/public_html/app/code/community/Reload/Seo/Model/Observer.php(31): Reload_Seo_Model_Observer->_registerScore('11', 'category', Object(Mage_Catalog_Model_Category))
#3 /home/user/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(1338): Reload_Seo_Model_Observer->catalogCategoryLoadAfter(Object(Varien_Event_Observer))
#4 /home/user/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Reload_Seo_Model_Observer), 'catalogCategory...', Object(Varien_Event_Observer))
#5 /home/user/domains/domain.com/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('catalog_categor...', Array)
#6 /home/user/domains/domain.com/public_html/app/code/core/Mage/Core/Model/Abstract.php(267): Mage::dispatchEvent('catalog_categor...', Array)
#7 /home/user/domains/domain.com/public_html/app/code/core/Mage/Core/Model/Abstract.php(226): Mage_Core_Model_Abstract->_afterLoad()
#8 /home/user/domains/domain.com/public_html/app/code/local/Proteus/Webmarketconfig/Block/Navigationcustom.php(338): Mage_Core_Model_Abstract->load('11')
#9 /home/user/domains/domain.com/public_html/app/design/frontend/webmarket/default/template/page/html/topmenu.phtml(28): Proteus_Webmarketconfig_Block_Navigationcustom->getWebmarketMenuHtml()
#10 /home/user/domains/domain.com/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/user...')
#11 /home/user/domains/domain.com/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/webmar...')
```

**Comment by jeljer-te-wies** [comment]
Hi Barryvdh, 

Thanxs for the using the plugin! 
We will get back to you asap.

**Comment by jeljer-te-wies** [comment]
Barryvdh

This error normally gets generated when you install the plugin with "compilation mode" enabled.
Can you disable compilation at system -> tools -> compilation

After you disabled compilation or if compilation was already disabled please clear the cache (login with FTP or SSH and empty the following directories): 
var/cache
var/session
var/locks

Let us know if this works!

**Comment by barryvdh** [comment]
Compilation was disabled:

> Compiler Status: Disabled
> Compilation State: Not Compiled

I also flushed the cache + logged out from admin and back in.

**Comment by jeljer-te-wies** [comment]
Thanks for the quick reply, can you email me your webshop url at lukas@reloadseo.com please? We will take a look at it and get back to you as soon as possible.

**Comment by arnokristiaan** [comment]
Hi Barryvdh,

I'm sorry but we already knew about this bug, the fix was created but somehow not committed. Version 1.2.2 is now available which contains the fix. The only file that was changed is the Observer.php file which can be found in app/code/community/Reload/Seo/Model/

**Comment by barryvdh** [comment]
@arnokristiaan Thank you, commit https://github.com/reloadseo/magento-plugin/commit/23026bdfcb0f9582075987924c7887b049ebd6ab indeed solves my issue!

@reloadseo Lukas, bedankt voor de uitleg dinsdagavond. Erg interessant! Ik ga het zeker even rustig bekijken allemaal.

**Comment by Mic2005** [comment]
I tested the new files and the error is gone. Working now here :)

Micha
