### ISSUE TITLE
verwarrende repository naam

### ISSUE THREAD

**Issue by hans2103** [reloadseo/magento-plugin#8]
Ik installeer al de magento extensies middels modman.
In de directory .modman staan alle uitbreidingen van Magento.
- aw_blog -> AheadWorks Blog
- Aoe_Scheduler -> Cron Scheduler van Fabrizio Branca
- magento-plugin -> dju... van wie is die nou weer. 

Is de laatstgenoemde van Bitpay of ReloadSEO?
- https://github.com/bitpay/magento-plugin
- https://github.com/reloadseo/magento-plugin

Het zou voor mij (en mogelijk andere) beheerders makkelijker zijn als jullie de repository zouden hernoemen van magento-plugin naar een meer specifieke naam voor jullie onderneming en plugin. Bijvoorbeeld RS_ReloadSEO

**Comment by Mic2005** [comment]
Ja, prima voorstel. Ik liep daar ook al tegen aan
